[package]
name = "kaleidoscope"
version = "0.1.0"
authors = ["BookOwl <stanleybookowl@gmail.com>"]

build = "build.rs"

[dependencies]
llvm-alt = { git = "https://github.com/TomBebb/llvm-rs.git"}

[build-dependencies]
gcc = "0.3"
semver = "0.1"
